// <auto-generated />
using System;
using EEM4QC_HFT_2021221.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EEM4QC_HFT_2021221.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211206114115_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.ExitedEmployeeModel", b =>
                {
                    b.Property<int>("Exit_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExitDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Exit_Id");

                    b.ToTable("Exited_Employee_Model");

                    b.HasData(
                        new
                        {
                            Exit_Id = 4,
                            ExitDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitDetail = "passport number 2345678",
                            Name = "Zeynab",
                            Surname = "Rahim"
                        },
                        new
                        {
                            Exit_Id = 5,
                            ExitDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitDetail = "passport number C2345671",
                            Name = "Oktay",
                            Surname = "Mammadov"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployee", b =>
                {
                    b.Property<int>("Emp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Emp_Is_Existed")
                        .HasColumnType("bit");

                    b.Property<string>("Emp_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_Id");

                    b.ToTable("Hr_Employees");

                    b.HasData(
                        new
                        {
                            Emp_Id = 1,
                            Emp_Is_Existed = true,
                            Emp_Name = "Sevinj",
                            Emp_Surname = "Abdullayeva"
                        },
                        new
                        {
                            Emp_Id = 2,
                            Emp_Is_Existed = true,
                            Emp_Name = "James",
                            Emp_Surname = "Bond"
                        },
                        new
                        {
                            Emp_Id = 3,
                            Emp_Is_Existed = true,
                            Emp_Name = "Ilkin",
                            Emp_Surname = "Mammad"
                        },
                        new
                        {
                            Emp_Id = 4,
                            Emp_Is_Existed = true,
                            Emp_Name = "Zeynab",
                            Emp_Surname = "Rahim"
                        },
                        new
                        {
                            Emp_Id = 5,
                            Emp_Is_Existed = true,
                            Emp_Name = "Oktay",
                            Emp_Surname = "Mammadov"
                        },
                        new
                        {
                            Emp_Id = 6,
                            Emp_Is_Existed = true,
                            Emp_Name = "Buse",
                            Emp_Surname = "Su"
                        },
                        new
                        {
                            Emp_Id = 7,
                            Emp_Is_Existed = true,
                            Emp_Name = "Altay",
                            Emp_Surname = "Aliyev"
                        },
                        new
                        {
                            Emp_Id = 8,
                            Emp_Is_Existed = true,
                            Emp_Name = "Olive",
                            Emp_Surname = "Mah"
                        },
                        new
                        {
                            Emp_Id = 9,
                            Emp_Is_Existed = true,
                            Emp_Name = "Tommy",
                            Emp_Surname = "Tomson"
                        },
                        new
                        {
                            Emp_Id = 10,
                            Emp_Is_Existed = true,
                            Emp_Name = "Saleh",
                            Emp_Surname = "Terim"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeCredentials", b =>
                {
                    b.Property<int>("Empc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Empc_EmployeeEmp_Id")
                        .HasColumnType("int");

                    b.Property<int>("Empc_Employee_Id")
                        .HasColumnType("int");

                    b.Property<string>("Empc_Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empc_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Empc_Id");

                    b.HasIndex("Empc_EmployeeEmp_Id");

                    b.ToTable("Hr_Employee_Credentials");

                    b.HasData(
                        new
                        {
                            Empc_Id = 1,
                            Empc_Employee_Id = 1,
                            Empc_Mail = "sevinj160@yahoo.com",
                            Empc_Password = "sevinj"
                        },
                        new
                        {
                            Empc_Id = 2,
                            Empc_Employee_Id = 2,
                            Empc_Mail = "james@yahoo.com",
                            Empc_Password = "oktay"
                        },
                        new
                        {
                            Empc_Id = 3,
                            Empc_Employee_Id = 3,
                            Empc_Mail = "ilkin@yahoo.com",
                            Empc_Password = "ilkin123"
                        },
                        new
                        {
                            Empc_Id = 4,
                            Empc_Employee_Id = 4,
                            Empc_Mail = "zeynab@yahoo.com",
                            Empc_Password = "zeynab1"
                        },
                        new
                        {
                            Empc_Id = 5,
                            Empc_Employee_Id = 5,
                            Empc_Mail = "oktay@yahoo.com",
                            Empc_Password = "oktay27"
                        },
                        new
                        {
                            Empc_Id = 6,
                            Empc_Employee_Id = 6,
                            Empc_Mail = "buse@yahoo.com",
                            Empc_Password = "buse1"
                        },
                        new
                        {
                            Empc_Id = 7,
                            Empc_Employee_Id = 7,
                            Empc_Mail = "altay@yahoo.com",
                            Empc_Password = "altay1"
                        },
                        new
                        {
                            Empc_Id = 8,
                            Empc_Employee_Id = 8,
                            Empc_Mail = "olive@yahoo.com",
                            Empc_Password = "olive1"
                        },
                        new
                        {
                            Empc_Id = 9,
                            Empc_Employee_Id = 9,
                            Empc_Mail = "tommy@yahoo.com",
                            Empc_Password = "tommy1"
                        },
                        new
                        {
                            Empc_Id = 10,
                            Empc_Employee_Id = 10,
                            Empc_Mail = "saleh@yahoo.com",
                            Empc_Password = "saleh1"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeExitDetail", b =>
                {
                    b.Property<int>("Eed_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Eed_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eed_Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Eed_Employee_Work_Details_Id")
                        .HasColumnType("int");

                    b.Property<int>("Eed_Interviewer")
                        .HasColumnType("int");

                    b.Property<string>("Eed_Questions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Eed_Id");

                    b.ToTable("Hr_Employee_Exit_Detail");

                    b.HasData(
                        new
                        {
                            Eed_Id = 1,
                            Eed_Date = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number C234567",
                            Eed_Employee_Work_Details_Id = 1,
                            Eed_Interviewer = 1,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 2,
                            Eed_Date = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number C2345676",
                            Eed_Employee_Work_Details_Id = 2,
                            Eed_Interviewer = 2,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 3,
                            Eed_Date = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number 546789",
                            Eed_Employee_Work_Details_Id = 3,
                            Eed_Interviewer = 3,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 4,
                            Eed_Date = new DateTime(2022, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number 2345678",
                            Eed_Employee_Work_Details_Id = 4,
                            Eed_Interviewer = 4,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 5,
                            Eed_Date = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number C2345671",
                            Eed_Employee_Work_Details_Id = 5,
                            Eed_Interviewer = 5,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 6,
                            Eed_Date = new DateTime(2022, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number C2656341",
                            Eed_Employee_Work_Details_Id = 6,
                            Eed_Interviewer = 6,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 7,
                            Eed_Date = new DateTime(2022, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number 34567876",
                            Eed_Employee_Work_Details_Id = 7,
                            Eed_Interviewer = 7,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 8,
                            Eed_Date = new DateTime(2022, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number 98765431",
                            Eed_Employee_Work_Details_Id = 8,
                            Eed_Interviewer = 8,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 9,
                            Eed_Date = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number C2309871",
                            Eed_Employee_Work_Details_Id = 9,
                            Eed_Interviewer = 9,
                            Eed_Questions = "non"
                        },
                        new
                        {
                            Eed_Id = 10,
                            Eed_Date = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Eed_Details = "passport number C2345991",
                            Eed_Employee_Work_Details_Id = 10,
                            Eed_Interviewer = 10,
                            Eed_Questions = "non"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeSalaryRecord", b =>
                {
                    b.Property<int>("Esr_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Esr_Amount")
                        .HasColumnType("float");

                    b.Property<double>("Esr_Currency")
                        .HasColumnType("float");

                    b.Property<DateTime>("Esr_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Esr_Employee_Id")
                        .HasColumnType("int");

                    b.Property<byte>("Esr_Frequency")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Esr_Hours")
                        .HasColumnType("tinyint");

                    b.Property<int>("Esr_Over_Time")
                        .HasColumnType("int");

                    b.Property<byte>("Esr_Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Esr_Id");

                    b.ToTable("Hr_Employee_Salary_Record");

                    b.HasData(
                        new
                        {
                            Esr_Id = 1,
                            Esr_Amount = 2000.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 1,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)1,
                            Esr_Over_Time = 1,
                            Esr_Type = (byte)1
                        },
                        new
                        {
                            Esr_Id = 2,
                            Esr_Amount = 2500.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 2,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)2,
                            Esr_Over_Time = 2,
                            Esr_Type = (byte)2
                        },
                        new
                        {
                            Esr_Id = 3,
                            Esr_Amount = 3000.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 3,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)3,
                            Esr_Over_Time = 3,
                            Esr_Type = (byte)3
                        },
                        new
                        {
                            Esr_Id = 4,
                            Esr_Amount = 4000.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 4,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)4,
                            Esr_Over_Time = 4,
                            Esr_Type = (byte)4
                        },
                        new
                        {
                            Esr_Id = 5,
                            Esr_Amount = 5000.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 5,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)5,
                            Esr_Over_Time = 5,
                            Esr_Type = (byte)5
                        },
                        new
                        {
                            Esr_Id = 6,
                            Esr_Amount = 300.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 6,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)6,
                            Esr_Over_Time = 6,
                            Esr_Type = (byte)6
                        },
                        new
                        {
                            Esr_Id = 7,
                            Esr_Amount = 10000.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 7,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)7,
                            Esr_Over_Time = 7,
                            Esr_Type = (byte)7
                        },
                        new
                        {
                            Esr_Id = 8,
                            Esr_Amount = 30000.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 8,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)8,
                            Esr_Over_Time = 8,
                            Esr_Type = (byte)8
                        },
                        new
                        {
                            Esr_Id = 9,
                            Esr_Amount = 9000.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 9,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)9,
                            Esr_Over_Time = 9,
                            Esr_Type = (byte)9
                        },
                        new
                        {
                            Esr_Id = 10,
                            Esr_Amount = 11000.0,
                            Esr_Currency = 0.0,
                            Esr_Date = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Esr_Employee_Id = 10,
                            Esr_Frequency = (byte)0,
                            Esr_Hours = (byte)10,
                            Esr_Over_Time = 10,
                            Esr_Type = (byte)10
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeStatus", b =>
                {
                    b.Property<int>("Emps_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Emps_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emps_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emps_Id");

                    b.ToTable("Hr_Employee_Status");

                    b.HasData(
                        new
                        {
                            Emps_Id = 1,
                            Emps_Description = "1 year experience",
                            Emps_Title = "Web designer"
                        },
                        new
                        {
                            Emps_Id = 2,
                            Emps_Description = "2 years experience",
                            Emps_Title = "Database administrator"
                        },
                        new
                        {
                            Emps_Id = 3,
                            Emps_Description = "3 years experience",
                            Emps_Title = "Programmer"
                        },
                        new
                        {
                            Emps_Id = 4,
                            Emps_Description = "4 years experience",
                            Emps_Title = "Manager"
                        },
                        new
                        {
                            Emps_Id = 5,
                            Emps_Description = "5 years experience",
                            Emps_Title = "Developer"
                        },
                        new
                        {
                            Emps_Id = 6,
                            Emps_Description = "3 months experience",
                            Emps_Title = "Jr. developer"
                        },
                        new
                        {
                            Emps_Id = 7,
                            Emps_Description = "7 years experience",
                            Emps_Title = "Assistant"
                        },
                        new
                        {
                            Emps_Id = 8,
                            Emps_Description = "8 years experience",
                            Emps_Title = "Director"
                        },
                        new
                        {
                            Emps_Id = 9,
                            Emps_Description = "9 years experience",
                            Emps_Title = "Teacher"
                        },
                        new
                        {
                            Emps_Id = 10,
                            Emps_Description = "10 years experience",
                            Emps_Title = "Driver"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeWorkDetails", b =>
                {
                    b.Property<int>("Wd_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Wd_About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wd_Employee_Exit_Detail_Id")
                        .HasColumnType("int");

                    b.Property<int>("Wd_Employee_Id")
                        .HasColumnType("int");

                    b.Property<int>("Wd_Employee_Status_Id")
                        .HasColumnType("int");

                    b.Property<int>("Wd_Experience")
                        .HasColumnType("int");

                    b.Property<bool>("Wd_Is_Exited")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Wd_Join_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Wd_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wd_Manager")
                        .HasColumnType("int");

                    b.Property<string>("Wd_Summary_Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wd_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wd_Work_Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wd_Work_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Wd_Id");

                    b.ToTable("Hr_Employee_Work_Details");

                    b.HasData(
                        new
                        {
                            Wd_Id = 1,
                            Wd_About = "junior 1",
                            Wd_Employee_Exit_Detail_Id = 1,
                            Wd_Employee_Id = 1,
                            Wd_Employee_Status_Id = 1,
                            Wd_Experience = 1,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Budapest",
                            Wd_Manager = 0,
                            Wd_Title = "Web designer",
                            Wd_Work_Mail = "sevinj160@yahoo.com",
                            Wd_Work_Phone = "36203106684"
                        },
                        new
                        {
                            Wd_Id = 2,
                            Wd_About = "junior 2",
                            Wd_Employee_Exit_Detail_Id = 2,
                            Wd_Employee_Id = 2,
                            Wd_Employee_Status_Id = 2,
                            Wd_Experience = 2,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Debrecen",
                            Wd_Manager = 0,
                            Wd_Title = "Database administrator",
                            Wd_Work_Mail = "james@yahoo.com",
                            Wd_Work_Phone = "36207896656"
                        },
                        new
                        {
                            Wd_Id = 3,
                            Wd_About = "junior 3",
                            Wd_Employee_Exit_Detail_Id = 3,
                            Wd_Employee_Id = 3,
                            Wd_Employee_Status_Id = 3,
                            Wd_Experience = 3,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Baku",
                            Wd_Manager = 0,
                            Wd_Title = "Programmer",
                            Wd_Work_Mail = "ilkin@yahoo.com",
                            Wd_Work_Phone = "99450896656"
                        },
                        new
                        {
                            Wd_Id = 4,
                            Wd_About = "senior 4",
                            Wd_Employee_Exit_Detail_Id = 4,
                            Wd_Employee_Id = 4,
                            Wd_Employee_Status_Id = 4,
                            Wd_Experience = 4,
                            Wd_Is_Exited = true,
                            Wd_Join_Date = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Zagatala",
                            Wd_Manager = 0,
                            Wd_Title = "Manager",
                            Wd_Work_Mail = "zeynab@yahoo.com",
                            Wd_Work_Phone = "99450797756"
                        },
                        new
                        {
                            Wd_Id = 5,
                            Wd_About = "senior 5",
                            Wd_Employee_Exit_Detail_Id = 5,
                            Wd_Employee_Id = 5,
                            Wd_Employee_Status_Id = 5,
                            Wd_Experience = 5,
                            Wd_Is_Exited = true,
                            Wd_Join_Date = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Prague",
                            Wd_Manager = 0,
                            Wd_Title = "Developer",
                            Wd_Work_Mail = "oktay@yahoo.com",
                            Wd_Work_Phone = "42045678756"
                        },
                        new
                        {
                            Wd_Id = 6,
                            Wd_About = "junior 3m",
                            Wd_Employee_Exit_Detail_Id = 6,
                            Wd_Employee_Id = 6,
                            Wd_Employee_Status_Id = 6,
                            Wd_Experience = 6,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(2021, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Paris",
                            Wd_Manager = 0,
                            Wd_Title = "Jr. developer",
                            Wd_Work_Mail = "buse@yahoo.com",
                            Wd_Work_Phone = "1550797756"
                        },
                        new
                        {
                            Wd_Id = 7,
                            Wd_About = "senior 7",
                            Wd_Employee_Exit_Detail_Id = 7,
                            Wd_Employee_Id = 7,
                            Wd_Employee_Status_Id = 7,
                            Wd_Experience = 7,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Istanbul",
                            Wd_Manager = 0,
                            Wd_Title = "Assistant",
                            Wd_Work_Mail = "altay@yahoo.com",
                            Wd_Work_Phone = "44250797756"
                        },
                        new
                        {
                            Wd_Id = 8,
                            Wd_About = "senior 8",
                            Wd_Employee_Exit_Detail_Id = 8,
                            Wd_Employee_Id = 8,
                            Wd_Employee_Status_Id = 8,
                            Wd_Experience = 8,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(2021, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Dresden",
                            Wd_Manager = 0,
                            Wd_Title = "Director",
                            Wd_Work_Mail = "olive@yahoo.com",
                            Wd_Work_Phone = "9945457756"
                        },
                        new
                        {
                            Wd_Id = 9,
                            Wd_About = "senior 9",
                            Wd_Employee_Exit_Detail_Id = 9,
                            Wd_Employee_Id = 9,
                            Wd_Employee_Status_Id = 9,
                            Wd_Experience = 9,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(2021, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "New York",
                            Wd_Manager = 0,
                            Wd_Title = "Teacher",
                            Wd_Work_Mail = "tommy@yahoo.com",
                            Wd_Work_Phone = "99450798760"
                        },
                        new
                        {
                            Wd_Id = 10,
                            Wd_About = "senior 10",
                            Wd_Employee_Exit_Detail_Id = 10,
                            Wd_Employee_Id = 10,
                            Wd_Employee_Status_Id = 10,
                            Wd_Experience = 10,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Miskolc",
                            Wd_Manager = 0,
                            Wd_Title = "Driver",
                            Wd_Work_Mail = "saleh@yahoo.com",
                            Wd_Work_Phone = "3620697756"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.UnExitedEmployeeModel", b =>
                {
                    b.Property<int>("Unexit_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Unexit_Id");

                    b.ToTable("UnExited_Employee_Model");

                    b.HasData(
                        new
                        {
                            Unexit_Id = 1,
                            JoinedDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Budapest",
                            Mail = "sevinj@yahoo.com",
                            Name = "Sevinj",
                            Phone = "36203106684",
                            Salary = 2000.0,
                            Summary = "non",
                            Surname = "Abdullayeva",
                            Title = "Sev"
                        },
                        new
                        {
                            Unexit_Id = 2,
                            JoinedDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Debrecen",
                            Mail = "james@yahoo.com",
                            Name = "James",
                            Phone = "36207896656",
                            Salary = 2500.0,
                            Summary = "non",
                            Surname = "Bond",
                            Title = "JamesB"
                        },
                        new
                        {
                            Unexit_Id = 3,
                            JoinedDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Baku",
                            Mail = "ilkin@yahoo.com",
                            Name = "Ilkin",
                            Phone = "99450896656",
                            Salary = 3000.0,
                            Summary = "non",
                            Surname = "Mammad",
                            Title = "IlkinM"
                        },
                        new
                        {
                            Unexit_Id = 6,
                            JoinedDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Paris",
                            Mail = "buse@yahoo.com",
                            Name = "Buse",
                            Phone = "1550797756",
                            Salary = 300.0,
                            Summary = "non",
                            Surname = "Su",
                            Title = "Buse"
                        },
                        new
                        {
                            Unexit_Id = 7,
                            JoinedDate = new DateTime(2022, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Istanbul",
                            Mail = "altay@yahoo.com",
                            Name = "Altay",
                            Phone = "44250797756",
                            Salary = 10000.0,
                            Summary = "non",
                            Surname = "Aliyev",
                            Title = "AltayA"
                        },
                        new
                        {
                            Unexit_Id = 8,
                            JoinedDate = new DateTime(2022, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Dresden",
                            Mail = "olive@yahoo.com",
                            Name = "OLive",
                            Phone = "9945457756",
                            Salary = 30000.0,
                            Summary = "non",
                            Surname = "Mah",
                            Title = "OliveM"
                        },
                        new
                        {
                            Unexit_Id = 9,
                            JoinedDate = new DateTime(2021, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "New York",
                            Mail = "tommy@yahoo.com",
                            Name = "Tommy",
                            Phone = "99450798760",
                            Salary = 9000.0,
                            Summary = "non",
                            Surname = "Tomson",
                            Title = "TommyT"
                        },
                        new
                        {
                            Unexit_Id = 10,
                            JoinedDate = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Miskolc",
                            Mail = "saleh@yahoo.com",
                            Name = "Saleh",
                            Phone = "3620697756",
                            Salary = 11000.0,
                            Summary = "non",
                            Surname = "Terim",
                            Title = "SalehT"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeCredentials", b =>
                {
                    b.HasOne("EEM4QC_HFT_2021221.Models.HrEmployee", "Empc_Employee")
                        .WithMany()
                        .HasForeignKey("Empc_EmployeeEmp_Id");

                    b.Navigation("Empc_Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
